SELECT TOP 1 BirthDay as NextBirthDay,
DATEPART(CONVERT(BirthDay, 'ddmm')
--DATEPART(wk,CONVERT(date, DATEPART(BirthDay, 104)) as WOD
FROM TestTask_170518
ORDER BY ABS(DATEPART(DAYOFYEAR,CONVERT(date, BirthDay, 104)) - DATEPART(DAYOFYEAR,GETDATE()))

SELECT TOP 1 BirthDay as LastBirthDay
FROM TestTask_170518
ORDER BY ABS(DATEPART(DAYOFYEAR,CONVERT(date, BirthDay, 104)) - DATEPART(DAYOFYEAR,GETDATE())) DESC


SELECT *,
CONVERT(date, BirthDay, 104) as WOD
--DATEPART(wk,CONVERT(date, DATEPART(BirthDay, 104)) as WOD
FROM TestTask_170518
ORDER BY ABS(DATEPART(DAYOFYEAR,CONVERT(date, BirthDay, 104)) - DATEPART(DAYOFYEAR,GETDATE()))


SELECT Receiver , (CONVERT(date, BirthDay, 104))  as NextBirth
FROM TestTask_170518
WHERE DATEPART(DAYOFYEAR,CONVERT(date, BirthDay, 104)) - DATEPART(DAYOFYEAR,GETDATE()) > 0


ORDER BY ABS(DATEPART(DAYOFYEAR,CONVERT(date, BirthDay, 104)) - DATEPART(DAYOFYEAR,GETDATE()))


